# Generated by Django 4.2 on 2023-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
